alias(
    name = "grpc_go",
    actual = "@@gazelle~~go_deps~org_golang_google_grpc//:go_default_library",
    visibility = [
        "//visibility:public",
    ],
)

alias(
    name = "grpc_credentials_insecure",
    actual = "@@gazelle~~go_deps~org_golang_google_grpc//credentials/insecure",
    visibility = [
        "//visibility:public",
    ],
)