apiVersion: v1
kind: Service
metadata:
  name: arithmetic-server-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: arithmetic-server
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
    name: grpc